highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://myjekyll.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# myjekyll.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Sudhir Shirsath's Resume
name: Sudhir Shirsath
email: sudhirs@protonmail.com
email_full: mailto:sudhirs@protonmail.com
website: github.io/zer0ttl
website_full: https://zer0ttl.github.io/
github: zer0ttl
twitter: zer0ttl
tel: +91 9823 904 937
tel_full: tel:+919823904937
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: Paud Road
  postcode: 411 004
  city: Pune
  country: India
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
